LOGISTIC REGRESSION
1. Data Exploration:
a. Load the dataset and perform exploratory data analysis (EDA).
b. Examine the features, their types, and summary statistics.
c. Create visualizations such as histograms, box plots, or pair plots to visualize the distributions and relationships between features.
Analyze any patterns or correlations observed in the data.
2. Data Preprocessing:
a. Handle missing values (e.g., imputation).
b. Encode categorical variables.
3. Model Building:
a. Build a logistic regression model using appropriate libraries (e.g., scikit-learn).
b. Train the model using the training data.
4. Model Evaluation:
a. Evaluate the performance of the model on the testing data using accuracy, precision, recall, F1-score, and ROC-AUC score.
Visualize the ROC curve.
5. Interpretation:
a. Interpret the coefficients of the logistic regression model.
b. Discuss the significance of features in predicting the target variable (survival probability in this case).
6. Deployment with Streamlit:
In this task, you will deploy your logistic regression model using Streamlit. The deployment can be done locally or online via Streamlit Share. Your task includes creating a Streamlit app in Python that involves loading your trained model and setting up user inputs for predictions.

(optional)For online deployment, use Streamlit Community Cloud, which supports deployment from GitHub repositories.
Detailed deployment instructions are available in the Streamlit Documentation.
https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app
Interview Questions:
1. What is the difference between precision and recall?
2. What is cross-validation, and why is it important in binary classification?

In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('/content/diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [7]:
df.size

6912

In [8]:
df.shape

(768, 9)

In [9]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [12]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [13]:
#split data into x and y
x=df.iloc[:,:8]
x
#when last column is the target then we take reverse index -1 or positive index

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [14]:
#everytime data is partioned into two times frist is x and y and next is train and test. if y is other than o and 1 then we can transform the data by df[outcome]=df['outcome'].replace({2:0,4:1}) if the outcome was 2 and 4
y=df['Outcome']
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Observations  
Glucose and BMI show strong relation with diabetes outcome.  
Age and Pregnancies also influence diabetes prediction.  
Some columns contain outliers.  
Features are not on the same scale, so standardization is required.

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_sc=sc.fit_transform(x)
x_sc

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [16]:
#the above is array to conver to pd.frame
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_sc=sc.fit_transform(x)
x_sc= pd.DataFrame(x_sc)
x_sc

,0,1,2,3,4,5,6,7
0,0.639947,0.848324,0.149641,0.907270,-0.692891,0.204013,0.468492,1.425995
1,-0.844885,-1.123396,-0.160546,0.530902,-0.692891,-0.684422,-0.365061,-0.190672
2,1.233880,1.943724,-0.263941,-1.288212,-0.692891,-1.103255,0.604397,-0.105584
3,-0.844885,-0.998208,-0.160546,0.154533,0.123302,-0.494043,-0.920763,-1.041549
4,-1.141852,0.504055,-1.504687,0.907270,0.765836,1.409746,5.484909,-0.020496
...,...,...,...,...,...,...,...,...
763,1.827813,-0.622642,0.356432,1.722735,0.870031,0.115169,-0.908682,2.532136
764,-0.547919,0.034598,0.046245,0.405445,-0.692891,0.610154,-0.398282,-0.531023
765,0.342981,0.003301,0.149641,0.154533,0.279594,-0.735190,-0.685193,-0.275760
766,-0.844885,0.159787,-0.470732,-1.288212,-0.692891,-0.240205,-0.371101,1.170732
767,-0.844885,-0.873019,0.046245,0.656358,-0.692891,-0.202129,-0.473785,-0.871374

In [17]:
x_sc.columns = list(x)
x_sc

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.639947,0.848324,0.149641,0.907270,-0.692891,0.204013,0.468492,1.425995
1,-0.844885,-1.123396,-0.160546,0.530902,-0.692891,-0.684422,-0.365061,-0.190672
2,1.233880,1.943724,-0.263941,-1.288212,-0.692891,-1.103255,0.604397,-0.105584
3,-0.844885,-0.998208,-0.160546,0.154533,0.123302,-0.494043,-0.920763,-1.041549
4,-1.141852,0.504055,-1.504687,0.907270,0.765836,1.409746,5.484909,-0.020496
...,...,...,...,...,...,...,...,...
763,1.827813,-0.622642,0.356432,1.722735,0.870031,0.115169,-0.908682,2.532136
764,-0.547919,0.034598,0.046245,0.405445,-0.692891,0.610154,-0.398282,-0.531023
765,0.342981,0.003301,0.149641,0.154533,0.279594,-0.735190,-0.685193,-0.275760
766,-0.844885,0.159787,-0.470732,-1.288212,-0.692891,-0.240205,-0.371101,1.170732
767,-0.844885,-0.873019,0.046245,0.656358,-0.692891,-0.202129,-0.473785,-0.871374

In [18]:
#modelbuilding
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_sc, y)

LogisticRegression()

In [19]:
model.predict_proba(x_sc) # 1st index is probability values and 0 index is 1-probability value

array([[0.28211443, 0.71788557],
       [0.94995783, 0.05004217],
       [0.2083351 , 0.7916649 ],
       ...,
       [0.82748394, 0.17251606],
       [0.71369402, 0.28630598],
       [0.92655547, 0.07344453]])

In [20]:
df['prob_value']=model.predict_proba(x_sc)[:,1]
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,prob_value
0,6,148,72,35,0,33.6,0.627,50,1,0.717886
1,1,85,66,29,0,26.6,0.351,31,0,0.050042
2,8,183,64,0,0,23.3,0.672,32,1,0.791665
3,1,89,66,23,94,28.1,0.167,21,0,0.042929
4,0,137,40,35,168,43.1,2.288,33,1,0.898647
...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,0.320797
764,2,122,70,27,0,36.8,0.340,27,0,0.318276
765,5,121,72,23,112,26.2,0.245,30,0,0.172516
766,1,126,60,0,0,30.1,0.349,47,1,0.286306
767,1,93,70,31,0,30.4,0.315,23,0,0.073445

In [21]:
df['y_pred'] = model.predict(x_sc)
df['y_pred'] #gives the above value in single line

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    0
767    0
Name: y_pred, Length: 768, dtype: int64

In [22]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,prob_value,y_pred
0,6,148,72,35,0,33.6,0.627,50,1,0.717886,1
1,1,85,66,29,0,26.6,0.351,31,0,0.050042,0
2,8,183,64,0,0,23.3,0.672,32,1,0.791665,1
3,1,89,66,23,94,28.1,0.167,21,0,0.042929,0
4,0,137,40,35,168,43.1,2.288,33,1,0.898647,1
...,...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,0.320797,0
764,2,122,70,27,0,36.8,0.340,27,0,0.318276,0
765,5,121,72,23,112,26.2,0.245,30,0,0.172516,0
766,1,126,60,0,0,30.1,0.349,47,1,0.286306,0
767,1,93,70,31,0,30.4,0.315,23,0,0.073445,0

#Question: I am unable to understand the column 1 and 0 here not sure fom where it appears in the above df!!



#confusion matrix is a evaluation or performance tool used in classification problem with having diff parameters.

CM:true negative TN
true positive TP
false negative FN
false positive FP

O IS NEG
1 IS POSITIVE

accuracy_score = TN+TP/TN+TP+FP+FN

precescion is TP/TP+FP

In [23]:
#model evaluation
from sklearn.metrics import confusion_matrix, accuracy_score,recall_score,precision_score, f1_score,log_loss, roc_curve, roc_auc_score
cm=confusion_matrix(y,df['y_pred'])
cm
#the diagonal values are accuracy and other diagonal 112 and 54 are error. CM is an evaluation matrix for classification problem.

array([[446,  54],
       [112, 156]])

In [24]:
score = accuracy_score(y,df['y_pred'])
print('accuracy score:', np.round(score,3)) #model score

accuracy score: 0.784

In [25]:
recall=recall_score(y,df['y_pred'])
print('recall_Score:',np.round(recall,3)) #recall is important where FN is critical

recall_Score: 0.582

In [26]:
TN,FP,FN,TP= confusion_matrix(y,df['y_pred']).ravel()
print('True Negative:',TN)
print('False Positive:',FP)
print('False Negative:',FN)
print('True Positive:',TP) #ravel/sensitivity converts multi dimentsional data into One Dimension. with the help of ravel function we have stored the values to the variables

True Negative: 446
False Positive: 54
False Negative: 112
True Positive: 156

In [27]:
Specificity = TN/(TN+FP)
print('Specificity:', np.round(Specificity,3)) #FP is critical

Specificity: 0.892

In [28]:
precision =precision_score(y,df['y_pred'])
print('preciscion:',np.round(precision,3))

preciscion: 0.743

In [29]:
f1_sc = f1_score(y,df['y_pred'])
print('f1_score:',np.round(f1_sc))

f1_score: 1.0

In [30]:
logloss = log_loss(y,df['prob_value'])
print('log_loss:',np.round(logloss,3)) # log loss is actually comparing your actual value to prob value

log_loss: 0.471

In [31]:
#ROC curve is a reciever operator charachterestic curve. it is an evaluiation tool for logistic model performances
fpr,tpr,thresholds = roc_curve(y,df['y_pred'])

In [32]:
#to identify accuracy we need auc score
AUC = roc_auc_score(y,df['y_pred'])
print('AUC:',np.round(AUC,3))

AUC: 0.737

Interview Questions:

# What is the difference between precision and recall?

Precision and recall are two fundamental metrics used in classification problems: They focus on different aspects of correctness:
#Precision
measures how many of the items predicted as positive are actually correct.

Precision = True Positives/ True Positives + False Positives
“When the model says yes, how often is it right?”

#Recall
measures how many of the actual positive cases the model successfully identified.

Recall=True Positives/True Positives + False Negatives
'Out of all real positive cases, how many did the model catch?”


# What is cross-validation, and why is it important in binary classification?

Cross-validation is a technique used to evaluate how well a model will generalize to unseen data. In machine learning, especially binary classification, it helps estimate whether a model is genuinely learning patterns or just memorizing the training set.

In [33]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,prob_value,y_pred
0,6,148,72,35,0,33.6,0.627,50,1,0.717886,1
1,1,85,66,29,0,26.6,0.351,31,0,0.050042,0
2,8,183,64,0,0,23.3,0.672,32,1,0.791665,1
3,1,89,66,23,94,28.1,0.167,21,0,0.042929,0
4,0,137,40,35,168,43.1,2.288,33,1,0.898647,1
...,...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,0.320797,0
764,2,122,70,27,0,36.8,0.340,27,0,0.318276,0
765,5,121,72,23,112,26.2,0.245,30,0,0.172516,0
766,1,126,60,0,0,30.1,0.349,47,1,0.286306,0
767,1,93,70,31,0,30.4,0.315,23,0,0.073445,0

#DATA PARTITION
why we need data partition?
to test the performance of the model on unseen or test data

Data is divided into training  phase and testing phase it can eb of any ratio 80/20, 70/30, 75/25

x tain y train
x test y test are 4 important variables here
suppose [1000,10] data then 80/20 distribution
Training : x train(800,9), y train (800,1)
testing: x train(200,9), y train(200,1)

model.fit(x-train, y-train)
model.predict(x-train)
model.predict(x-test)
model evaluation(error, accuracy)

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x_sc,y,test_size=0.2, random_state=1)

In [35]:
x_train.shape

(614, 8)

In [36]:
x_test.shape

(154, 8)

In [37]:
y_train.shape

(614,)

In [38]:
y_test.shape

(154,)

In [39]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [40]:
y_pred_train= model.predict(x_train)
y_pred_train

array([1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0])

In [41]:
y_pred_test= model.predict(x_test)
y_pred_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0])

Model testing on Unseen data: Initial evaluation is only for understanding. Final evaluation should always be done using test data

In [42]:
from sklearn.metrics import accuracy_score, classification_report
accuracy_train = accuracy_score(y_train,y_pred_train)
print('Training_accuracy:', np.round(accuracy_train,3))

Training_accuracy: 0.775

In [43]:
accuracy_test = accuracy_score(y_test,y_pred_test)
print('Testing_accuracy:', np.round(accuracy_test,3))

Testing_accuracy: 0.779

#crossvalidation: you are cross validating your testing result.
there are different techniques for cross validation
1. shuffle split and
2. Kfold

In [44]:
#shuffle split
train_acc =[]
test_acc=[]

for i in range(1,101):
  x_train,x_test,y_train,y_test=train_test_split(x_sc,y,test_size=0.2, random_state=i)
  model.fit(x_train,y_train)
  y_pred_train=model.predict(x_train)
  y_pred_test=model.predict(x_test)
  train_acc.append(accuracy_score(y_train,y_pred_train))
  test_acc.append(accuracy_score(y_test,y_pred_test))

In [45]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, x_sc, y, cv=5)

print(scores)
print(scores.mean())

[0.77272727 0.74675325 0.75324675 0.81699346 0.76470588]
0.7708853238265002

In [46]:
len(train_acc)

100

In [47]:
len(test_acc)

100

In [48]:
print('Shuffle split-Training accuracy:', np.round(np.mean(train_acc),3))
print('Shuffle split-Testing accuracy:', np.round(np.mean(test_acc),3)) # this is used only for small data set

Shuffle split-Training accuracy: 0.779
Shuffle split-Testing accuracy: 0.776

In [49]:
coef_df = pd.DataFrame({
    'Feature': x.columns,
    'Coefficient': model.coef_[0]
})

coef_df

                    Feature  Coefficient
0               Pregnancies     0.354201
1                   Glucose     1.162582
2             BloodPressure    -0.199701
3             SkinThickness    -0.053199
4                   Insulin    -0.086607
5                       BMI     0.736922
6  DiabetesPedigreeFunction     0.412847
7                       Age     0.247690

notes: Positive coefficient increases diabetes probability
Negative coefficient decreases probability

In [50]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

# Define parameter grid
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs'],
    'penalty': ['l2']
}

# Create model
log_model = LogisticRegression(max_iter=1000)

# Grid Search
grid_search = GridSearchCV(
    estimator=log_model,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy'
)

# Fit model
grid_search.fit(x_train, y_train)

# Best parameters
print("Best Parameters:", grid_search.best_params_)
print("Best Score:", grid_search.best_score_)

Best Parameters: {'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}
Best Score: 0.7882180461148873

In [51]:
from sklearn.metrics import accuracy_score, classification_report

# Make predictions with the best model from GridSearchCV
best_y_pred = grid_search.best_estimator_.predict(x_test)

# Accuracy
best_accuracy = accuracy_score(y_test, best_y_pred)
print("Tuned Model Accuracy:", best_accuracy)

# Classification Report
print(classification_report(y_test, best_y_pred))

Tuned Model Accuracy: 0.7337662337662337
              precision    recall  f1-score   support

           0       0.77      0.85      0.81       101
           1       0.64      0.51      0.57        53

    accuracy                           0.73       154
   macro avg       0.71      0.68      0.69       154
weighted avg       0.72      0.73      0.73       154

In [59]:
import joblib

joblib.dump(grid_search.best_estimator_, "diabetes_model.pkl")
joblib.dump(sc, "scaler.pkl")

['scaler.pkl']

In [60]:
%%writefile app.py

import streamlit as st
import joblib
import numpy as np

model = joblib.load("diabetes_model.pkl")
scaler = joblib.load("scaler.pkl")

st.title("Diabetes Prediction using Logistic Regression")

preg = st.number_input("Pregnancies", 0)
glucose = st.number_input("Glucose")
bp = st.number_input("Blood Pressure")
skin = st.number_input("Skin Thickness")
insulin = st.number_input("Insulin")
bmi = st.number_input("BMI")
dpf = st.number_input("Diabetes Pedigree Function")
age = st.number_input("Age")

if st.button("Predict"):
    data = np.array([[preg, glucose, bp, skin, insulin, bmi, dpf, age]])
    data = scaler.transform(data)
    prediction = model.predict(data)

    if prediction[0] == 1:
        st.error("Diabetic")
    else:
        st.success("Not Diabetic")

Overwriting app.py

In [56]:
%%writefile requirements.txt

streamlit
scikit-learn
pandas
numpy
joblib

Writing requirements.txt